# Generated by Django 4.1.5 on 2023-01-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emargement', '0002_rename_first_name_emargement_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emargement',
            old_name='created_at',
            new_name='date_inscription',
        ),
        migrations.AlterField(
            model_name='emargement',
            name='numero_telephone',
            field=models.IntegerField(max_length=255),
        ),
    ]
