# Generated by Django 4.1.5 on 2023-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emargement', '0003_rename_created_at_emargement_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emargement',
            name='numero_telephone',
            field=models.CharField(max_length=10),
        ),
    ]
